/*
 * Leaderboard for t-rex-runner.
 *
 * Submission flow (no embedded token — works around GitHub push protection
 * revoking any PAT that lands in git history):
 *   - On game over, the player enters a name and clicks Submit.
 *   - We open a prefilled "new issue" URL on GitHub. The player confirms the
 *     issue with their own GitHub account; a GitHub Actions workflow then
 *     extracts the score from the issue body and appends it to scores.json.
 *
 * Read flow:
 *   - Fetch scores.json (served via GitHub Pages) and render the Top 10.
 *   - Cached in localStorage for 5 minutes so repeat loads are fast.
 *
 * Hooks into the game via the custom window events 'dino:gameover' and
 * 'dino:restart' dispatched from index.js — no other coupling to the game.
 */
(function () {
    'use strict';

    var REPO = 'Religious-J/t-rex-runner';
    // scores.json is generated by the collect-scores workflow and served
    // from the same GitHub Pages site as the game.
    var SCORES_URL = 'scores.json';
    var NEW_ISSUE_URL = 'https://github.com/' + REPO + '/issues/new';
    var CACHE_KEY = 'dino_leaderboard_cache';
    var CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes
    var MAX_ENTRIES = 10;

    // ---- DOM ----
    var submitEl, leaderboardEl, nameInput, submitBtn, skipBtn, closeBtn, listEl;

    function buildUI() {
        // Score submission overlay (shown on game over).
        submitEl = document.createElement('div');
        submitEl.id = 'score-submit';
        submitEl.className = 'lb-hidden';
        submitEl.innerHTML =
            '<div class="lb-panel">' +
              '<h3>Game Over!</h3>' +
              '<p>Your score: <span id="lb-final-score">0</span></p>' +
              '<input id="lb-name" type="text" maxlength="16" placeholder="Your name" />' +
              '<p class="lb-hint">Submitting opens GitHub — just click "Submit new issue".</p>' +
              '<div class="lb-buttons">' +
                '<button id="lb-submit-btn">Submit</button>' +
                '<button id="lb-skip-btn" class="lb-secondary">Skip</button>' +
              '</div>' +
            '</div>';
        document.body.appendChild(submitEl);

        // Leaderboard panel (always visible below the game).
        leaderboardEl = document.createElement('div');
        leaderboardEl.id = 'leaderboard';
        leaderboardEl.innerHTML =
            '<div class="lb-header">' +
              '<h3>🏆 Leaderboard</h3>' +
              '<button id="lb-refresh" class="lb-secondary lb-small" title="Refresh">↻</button>' +
            '</div>' +
            '<ol id="lb-list"></ol>';
        document.querySelector('.interstitial-wrapper').appendChild(leaderboardEl);

        nameInput = document.getElementById('lb-name');
        submitBtn = document.getElementById('lb-submit-btn');
        skipBtn = document.getElementById('lb-skip-btn');
        closeBtn = document.getElementById('lb-refresh');
        listEl = document.getElementById('lb-list');

        submitBtn.addEventListener('click', onSubmit);
        skipBtn.addEventListener('click', hideSubmit);
        closeBtn.addEventListener('click', function () {
            fetchAndRender(true);
        });
        nameInput.addEventListener('keydown', function (e) {
            if (e.key === 'Enter') onSubmit();
        });
    }

    // ---- Score submission ----
    var currentScore = 0;
    var alreadySubmitted = false;

    function showSubmit(score) {
        currentScore = score;
        document.getElementById('lb-final-score').textContent = score;
        submitEl.classList.remove('lb-hidden');
        nameInput.value = '';
        nameInput.focus();
        alreadySubmitted = false;
    }

    function hideSubmit() {
        submitEl.classList.add('lb-hidden');
    }

    function onSubmit() {
        if (alreadySubmitted) {
            hideSubmit();
            return;
        }
        var name = (nameInput.value || '').trim().slice(0, 16) || 'Anonymous';
        alreadySubmitted = true;

        // Build a prefilled issue. title carries the score for quick scanning
        // in the issue list; body carries the JSON the workflow parses.
        var payload = { name: name, score: currentScore, ts: Date.now() };
        var title = 'score: ' + currentScore + ' (' + name + ')';
        var body = '```json\n' + JSON.stringify(payload) + '\n```';
        var url = NEW_ISSUE_URL +
            '?title=' + encodeURIComponent(title) +
            '&body=' + encodeURIComponent(body);

        // Open GitHub's "new issue" page in a new tab. The player confirms
        // there; the workflow picks up the resulting issue.
        window.open(url, '_blank');

        // Give a moment, then close the overlay. The leaderboard won't update
        // instantly — the workflow takes a few seconds to run and commit.
        submitBtn.textContent = 'Opened GitHub ✓';
        setTimeout(function () {
            submitBtn.textContent = 'Submit';
            hideSubmit();
        }, 1500);
    }

    // ---- Leaderboard fetch & render ----
    function getCache() {
        try {
            var raw = localStorage.getItem(CACHE_KEY);
            if (!raw) return null;
            var parsed = JSON.parse(raw);
            if (Date.now() - parsed.ts > CACHE_TTL_MS) return null;
            return parsed.data;
        } catch (e) {
            return null;
        }
    }

    function setCache(data) {
        try {
            localStorage.setItem(CACHE_KEY, JSON.stringify({ ts: Date.now(), data: data }));
        } catch (e) { /* ignore */ }
    }

    function fetchLeaderboard(cb) {
        var cached = getCache();
        if (cached) { cb(cached); return; }

        var xhr = new XMLHttpRequest();
        // Cache-bust so we pick up newly committed scores after the workflow
        // runs. GitHub Pages also sets its own CDN cache, but the query string
        // lets us force a fresh fetch on demand.
        xhr.open('GET', SCORES_URL + '?t=' + Date.now(), true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                if (xhr.status >= 200 && xhr.status < 300) {
                    try {
                        var data = JSON.parse(xhr.responseText);
                        var entries = Array.isArray(data) ? data : (data.scores || []);
                        entries.sort(function (a, b) { return b.score - a.score; });
                        entries = entries.slice(0, MAX_ENTRIES);
                        setCache(entries);
                        cb(entries);
                    } catch (e) {
                        cb(null);
                    }
                } else {
                    cb(null);
                }
            }
        };
        xhr.send();
    }

    function fetchAndRender(force) {
        if (force) {
            try { localStorage.removeItem(CACHE_KEY); } catch (e) { /* ignore */ }
        }
        fetchLeaderboard(function (entries) {
            renderLeaderboard(entries);
        });
    }

    function renderLeaderboard(entries) {
        listEl.innerHTML = '';
        if (!entries || entries.length === 0) {
            var empty = document.createElement('li');
            empty.className = 'lb-empty';
            empty.textContent = 'No scores yet. Be the first!';
            listEl.appendChild(empty);
            return;
        }
        for (var i = 0; i < entries.length; i++) {
            var li = document.createElement('li');
            var rank = document.createElement('span');
            rank.className = 'lb-rank';
            rank.textContent = (i + 1) + '.';
            var name = document.createElement('span');
            name.className = 'lb-name';
            name.textContent = entries[i].name;
            var score = document.createElement('span');
            score.className = 'lb-score';
            score.textContent = entries[i].score;
            li.appendChild(rank);
            li.appendChild(name);
            li.appendChild(score);
            listEl.appendChild(li);
        }
    }

    // ---- Wire up to game events ----
    function init() {
        buildUI();
        // Load the leaderboard on page open.
        fetchAndRender(false);
        // Refresh on focus (e.g. coming back to the tab after submitting).
        window.addEventListener('focus', function () { fetchAndRender(false); });

        window.addEventListener('dino:gameover', function (e) {
            var score = e && e.detail ? e.detail.score : 0;
            showSubmit(score);
        });
        window.addEventListener('dino:restart', function () {
            hideSubmit();
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
